site_dir: docs-site
site_name: Wind Programming Language
site_url: https://doc.wind-lang.me
site_description: Wind, designed for safety, simplicity, and performance.
site_author: utcq
use_directory_urls: true
nav:
  - Home: 'index.md'
  - Getting Started: 'learn/quick.md'
  - Syntax: 'learn/syntax.md'
  - About: 'about.md'

theme:
  name: terminal
  palette: gruvbox_dark

plugins:
  - search

remote_branch: docs-site

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/utcq/wind
