site_dir: docs-site
site_name: Wind Programming Language
use_directory_urls: false
nav:
  - Home: 'index.md'
  - Getting Started: '/#getting-started'
  - Troubleshooting: 'help.md'

theme:
  name: terminal
  palette: gruvbox_dark

plugins:
  - search

remote_branch: docs-site

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/utcq/wind