name: Deploy MkDocs site to GitHub Pages

on:
  push:
    branches:
      - docs  # Replace with the branch you are working on
  pull_request:
    branches:
      - docs  # Replace with the branch you are working on


jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install mkdocs mkdocs-terminal

      - name: Build and Deploy to GitHub Pages
        run: mkdocs gh-deploy --force
        env:
          MKDOCS_GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
